### ISSUE TITLE
Notes pop up function

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#100]
Bill,
Let's make the popup notes piece simple. 

If there is a note, then under any status, Approved, Conditional, Declined, etc. make the notes box pop up when first opening the application. This will ensure now notes are missed in the process. 

Can we add a checkbox that says "hide until next status"? This box would give the UW or salesman the ability to hide the box if they plan to work the deal multiple times in the interface. However, when the app moves to a new status and stage, the notes should pop up again to be read. 

If there is a "notification" icon for unread notes, that would be acceptable as well. 

Give it some thought and let us know what you think, too. 
The goal is to ensure the users do not miss a note.

**Comment by bbuchanan** [comment]
per our call, going to simply change the button color to indicate notes and text the salesperson when the status changes.
