### ISSUE TITLE
SSN MD5 Hash Before Submitting to Scoring API

### ISSUE THREAD

**Issue by sraghun** [bbuchanan/los-issues#101]
We need to do a MD5 Hash of the SSN before submitting that info to our scoring API.  In order to obfuscate the hash some more we throw in the following string in front of the SSN (which will include the dashes): AwerqfaOiupj; (the string includes the semi-colon)

For example, when you encounter the SSN string 398-52-4544, you do the following:
MD5Hash(AwerqfaOiupj;398-52-4544)

This should result in the following hashed string: 1a9ae8339b2a01bad5859db56139f6b2

**Comment by bbuchanan** [comment]
will be addressed in next release
