### ISSUE TITLE
desking stage - cannot submit

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#105]
![image](https://user-images.githubusercontent.com/59945434/76782534-ca90fe80-6786-11ea-9bfd-5553cf4d3d68.png)

got to desking stage, cannot save nor submit.

**Comment by bbuchanan** [comment]
The desking error is being sent back from AMS. When it's Desking, we submit it to AMS.

I think this is all stemmed from the missing co-buyer address because I went through the process on a new app that had proper address data and it worked.
