### ISSUE TITLE
Hourly Pay and Hours per week missing in LOS

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#111]
The fields associated with hourly pay and hour per week is not being parsed in the LOS application. 
Consequently, missing in the application print out.

**Comment by humike** [comment]
![image](https://user-images.githubusercontent.com/59945434/76999308-ce5e8580-692c-11ea-9902-af478d4f31db.png)

**Comment by bbuchanan** [comment]
will have this out for you shortly.
