### ISSUE TITLE
Payment value in Json file for score is inaccurate

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#112]
![image](https://user-images.githubusercontent.com/59945434/77000807-5180db00-692f-11ea-892c-59d83354b3ef.png)

Payment is wrong - way too big.  Payment amount needs to be the actual payment expected from the payment formula.

**Comment by bbuchanan** [comment]
I don't think I understand. Right now, payment amount is what they'll be paying throughout the life of the loan, I believe. So what does the "actual payment" indicate?

**Comment by humike** [comment]
Actual payment needs to be the single payment amount that the customer will be making overtime. 
So if a monthly payment is $400
The weekly would be $100
Semi-monthly would be $200

**Comment by bbuchanan** [comment]
Think we got to the bottom of this, will be in the next deploy.
