### ISSUE TITLE
Notes are out of order... 

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#113]
![image](https://user-images.githubusercontent.com/59945434/77001806-e6380880-6930-11ea-9dbf-72c4ef2ad965.png)

Please take a look at the order of the notes - for some reason they are not coming in the right order. Needs to show oldest at the top, newest at the bottom.

**Comment by bbuchanan** [comment]
do you think so? I would think newest at the top, right? Like email?

**Comment by bbuchanan** [comment]
I can see it either way, so lets go w/ your way. This will be sorted in the next deploy.
