### ISSUE TITLE
Bureau tabs and Vehicle tabs are swapped......? 

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#119]
![image](https://user-images.githubusercontent.com/59945434/77694070-ced7cb80-6f7f-11ea-9c7c-581f3ac477a3.png)
what's going on here?

**Comment by sraghun** [comment]
Bill, we are going live with the client tomorrow.  Can we get this one issue resolved?  Right now, the Bureau tab is displaying Vehicle information and Vehicle tab is displaying Bureau info.

**Comment by bbuchanan** [comment]
fixed
