### ISSUE TITLE
Loan Information card isn't right any more

### ISSUE THREAD

**Issue by bbuchanan** [bbuchanan/los-issues#26]
We've changed so many things in the deal at this stage that the fields don't really reflect what we have any longer. Probably needs the crew to determine what this should look like now.

For example, we don't have a program any longer. There is a deferred down payment and a cash down, what does the "downpayment" field on this card represent?

**Comment by humike** [comment]
Replace DownPayment with two new fields:
CashDown 
Net Trade

and
Remove Program

**Comment by bbuchanan** [comment]
Should be addressed in next deploy
