### ISSUE TITLE
Wierdness in displaying Co-Applicant Information

### ISSUE THREAD

**Issue by sraghun** [bbuchanan/los-issues#37]
I have application 30 pulled up in Chrome as a Underwriter.  When I pull up the CoApplicant information, I see the following odd behavior:

- Nothing is displayed when you click on Information tab
- Clicking on Bureau tab displays vehicle information
- Clicking on Custom Fields displays credit report
- Quote tab displays Custom Fields

Also, I think we should removed Quote tab from CoApplicant display

**Comment by bbuchanan** [comment]
A few things going on here that were addressed. Also removed the Quote tab from the CoApplicant display. This will be available in the next deploy.
