### ISSUE TITLE
Discuss and implement conditions when app is no longer editable.

### ISSUE THREAD

**Issue by bbuchanan** [bbuchanan/los-issues#41]
Lets outline all the cases where we should not be able to edit the app and how that looks (do not accept key presses, gray out the save button?)

**Comment by sraghun** [comment]
An app should NOT be editable under the following scenarios:

If logged in as a SalesPerson, then the app cannot be editable if it is in the following status:
Underwriting
Desked

If logged in as an Underwriter, then the app can't be edited if it is in the following status:
Sales
Desked

When an app is not editable, they should not be able to do the following actions as well:
Merge
Swap Buyer/Co-Buyer
Put in Notes

Ideally, I would like to make the app not accept key presses if it is not editable.

**Comment by bbuchanan** [comment]
Think I covered all of these scenarios. Will deploy later today for testing.
