### ISSUE TITLE
payment not recalculating after changing vehicle

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#44]
After changing the vehicle, the amount to finance and payment seems to calculate using the old vehicle ATF. It does not update given the new vehicle.

![image](https://user-images.githubusercontent.com/59945434/73757451-41be8600-4737-11ea-8a85-04f84a139d88.png)

**Comment by bbuchanan** [comment]
I'm not able to reproduce this problem. When I change the car, the prices update. Something peculiar with your price, it's 0 and I don't know why that is. Any ideas? Which app is this?

**Comment by humike** [comment]
This was app 37. I think it has to do with running through the application again. If I update fields again on the quote page, it looks like the values will update. But only if I hit backspace and then type in a new value for any of the fields. I am on Firefox, not sure if it's isolated to my instance.

**Comment by bbuchanan** [comment]
I think I figured this out. Fix will be deployed by 6pm tonight.
