### ISSUE TITLE
Paytype missing

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#45]
Through the build, we seemed to have dropped the Paytype field. This field is needed to determine how often a payment is made. At some point, it was mapped to the employment pay frequency, but that doesn't appear to change the paytype. Can you double check why this field was dropped?

![image](https://user-images.githubusercontent.com/59945434/73764532-31130d80-4741-11ea-919f-cc5bedfd9ece.png)

**Comment by bbuchanan** [comment]
put the field in between APR and Term.

**Comment by bbuchanan** [comment]
implemented.
