### ISSUE TITLE
Application edits not saving

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#48]
I made a number of changes to application 37, changing the vehicle, adding down payment, etc. 
When I hit save, the values do not update. Tried hitting save and submit. Both routes do not work. 

![image](https://user-images.githubusercontent.com/59945434/73768338-d4b2ec80-4746-11ea-88bf-e1eff86c12ff.png)

**Comment by bbuchanan** [comment]
yup, looks like I broke saving late on Friday. Figured out what was going on, will have this deployed this evening.
