### ISSUE TITLE
Print Quote Sheet missing fields

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#50]
The print quote sheet is missing the quoter page inputs section on the mockflow: https://wireframepro.mockflow.com/editor.jsp?editor=off&perm=Owner&projectid=Me1e5541c07e129590131ba934040995a1572630911068&publicid=786e2b17dac44653af058b6d6f14a1dd#/page/Dd8b535c395f4573e74e8660581f27f9e

![image](https://user-images.githubusercontent.com/59945434/73769943-90751b80-4749-11ea-97b3-22ad06acdda2.png

**Comment by humike** [comment]
![image](https://user-images.githubusercontent.com/59945434/73770107-d6ca7a80-4749-11ea-94c0-8a9f01aea229.png)

**Comment by bbuchanan** [comment]
Oh, I didn't realize you actually wanted this on the quote sheet itself. I thought it was a reference. Do you want it formatted like this?

**Comment by humike** [comment]
Yes, for V1, we need to have this for the seller to use and input into Auto Master.

**Comment by bbuchanan** [comment]
We don't have a tax %, only a tax amount. Is that OK?

**Comment by bbuchanan** [comment]
OK, implemented this.

**Comment by humike** [comment]
Yes, that's okay.
