### ISSUE TITLE
Notes Block to capture dialogue between Seller and UW

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#51]
At one point, we wanted to add a "notes" section to capture the dialogue between the Seller and Underwriter. Is this on the list of to-dos for v1? 
]

**Comment by humike** [comment]
this feature is required for V1

**Comment by bbuchanan** [comment]
Please tag it with v1 then.

**Comment by humike** [comment]
yeah... I don't have a tag option on my screen. How do you tag?
![image](https://user-images.githubusercontent.com/59945434/73862099-08a41580-480c-11ea-8a86-782664fde0ae.png)

**Comment by bbuchanan** [comment]
I'll take care of it.

**Comment by bbuchanan** [comment]
Added a Notes button to add and review app notes.
