### ISSUE TITLE
Credit Applicaiton doesn't seem to accept cobuyer

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#59]
I just tried uploading another application with a co-buyer, and I received this error.  When I remove the coapplicant, the applicaiton goes through.

![image](https://user-images.githubusercontent.com/59945434/73856974-3f762d80-4804-11ea-95cf-ced082563614.png)

**Comment by bbuchanan** [comment]
Looks like something to do w/ previous employment data that we're not expecting, can you get the json request please?

**Comment by bbuchanan** [comment]
assigned this to Sri per our call. He's going to follow up w/ David to see what data he's sending us. It seems to be choking on previous employment data from a co-applicant.

**Comment by bbuchanan** [comment]
Mike confirmed this is working now.
