### ISSUE TITLE
Previous Employment category not clear - unable to add in the UW tool

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#61]
When previous employment is added to the application, the fields show up in the UW app. Unfortunately, it's unclear which employment is current and which is previous. 

They are both labeled as "Company Details" 
Can we add a block of text which indicates whether it's a current employer or previous employer? 
Also, the UW app should give the user the ability to add a previous employer within the tool if they determine it's necessary. 

![image](https://user-images.githubusercontent.com/59945434/73858756-e8be2300-4806-11ea-85d2-cb54ee1ae65b.png)

**Comment by bbuchanan** [comment]
Current and previous employers are now identified.
