### ISSUE TITLE
Approval and Desking lacking gates and control

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#62]
Looks like I can approve and declines deals without entering a structure. 

In order for a deal to be approved, we need these items to be true. 
1. Employer Information must be entered
2. A vehicle with sales prices >0 must be selected. 
3. All the fields on the quote page must be populated with some value. 
4. Most importantly, the deal must be scored with a value greater than 0. 

In order to get to the approved status, those four things must be true. 

![image](https://user-images.githubusercontent.com/59945434/73859735-82d29b00-4808-11ea-8642-86d9bdb91a65.png)

**Comment by bbuchanan** [comment]
this will be addressed in the next build
