### ISSUE TITLE
Rows per page broken in Vehicle section

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#65]
When selecting to review more rows in the vehicle section, the list goes blank. Similar to what happened on the sales queue page. 

![image](https://user-images.githubusercontent.com/59945434/73860444-8dd9fb00-4809-11ea-9db8-2d9f7058b59f.png)

**Comment by bbuchanan** [comment]
good catch, this will be fixed in the next go. Will likely put it out there before our call at 4:30.
