### ISSUE TITLE
Deal with CoBuyer can still be merged - Fix so Deals wth a CoBuyer cannot Merge

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#67]
I merged an application with a co-buyer with another single application. The result drops the co-buyer attached to the first application. 

This is problematic because we have lost access to the second co-buyers information. I now have an orphaned co-buyer in the system which I cannot see and cannot attach to other deals. The only way to get this buyer's application back is through entering the app again. That would mean another hit to the credit and another ding to the cost. 

![image](https://user-images.githubusercontent.com/59945434/73860862-34260080-480a-11ea-8ed4-c487e7469d72.png)

**Comment by bbuchanan** [comment]
If there is a co-buyer, simply disallow merging.

**Comment by bbuchanan** [comment]
Merge feature removed if a cobuyer is on the app.
