### ISSUE TITLE
Quote Page - no data validation - in firefox

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#68]
Data Validation appears to be missing on the quote page. 

![image](https://user-images.githubusercontent.com/59945434/73861682-5bc99880-480b-11ea-9d45-b333f1264d77.png)

**Comment by bbuchanan** [comment]
As I've mentioned a few times, there is no validation anywhere in the application because we haven't talked about what is required, valid ranges, etc. I can start making best guesses, but it's better if it comes from you guys since you know exactly what they're supposed to be.

**Comment by humike** [comment]
Everything circled should have number validation with the option of 2 decimal places.

**Comment by bbuchanan** [comment]
I gotcha on that, I'm saying there's a bigger consideration.

**Comment by bbuchanan** [comment]
This is definitely a Firefox problem. The FF browser on any number field does not honor that field.

For example, go here.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

Then go there w/ anything but FF and you cannot type in numbers.

If the customer is using FF, we should take the time to disallow letters in number fields, but that's not a tiny task. I think time is better spent elsewhere, but that's just me.
