### ISSUE TITLE
Some fields are not captured/displayed correctly

### ISSUE THREAD

**Issue by sraghun** [bbuchanan/los-issues#69]
Some fields entered in the application form either don't have a place in the LOS display or are not captured correctly. I think some of these are critical to make a credit decision.

**Information Tab**
Marital Status
Ages of Dependents
Rent or Mortgage per month
Years at Address
Months at Address

**Employment Tab**
Hourly Pay
Hours Worked
Pay Period

**Income and Debt Tab**
Chapter 7, 11 or 13 is not captured correctly.  I put in Chapter 7 when keying in App #38 and it didn't come through
There are 2 amount owed fields??

**Comment by bbuchanan** [comment]
Close as issue #35 contains the merged issue.
