### ISSUE TITLE
Change order of custom fields

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#71]
Need to swap order of Custom fields. 
Change order to match the following: 

Auto Zoom ID:
Stability Score:
Structure Score:
Total Score:

![image](https://user-images.githubusercontent.com/59945434/73875134-bfab8b80-4822-11ea-8e8d-dd0e78a4fd07.png)

**Comment by bbuchanan** [comment]
note: currently nothing to support ordering of fields. If we want to do this for v1, lets discuss how we set an order.

**Comment by humike** [comment]
Lets relabel the custom field AutoZoom to "Stability Score"

**Comment by humike** [comment]
and you can forget about ordering the rows. Simply change the name.

**Comment by bbuchanan** [comment]
Got it.
