### ISSUE TITLE
Housing Status is not being pushed correctly to AMS

### ISSUE THREAD

**Issue by sraghun** [bbuchanan/los-issues#72]
Housing Status was blank for the apps that were pushed to AMS.  Please check if we are sending the data.

**Comment by bbuchanan** [comment]
I don't think they support it. Here is the class structure David sent me.

public class Applicant
    {       
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public DateTime DOB { get; set; }
        public string SSN { get; set; }
        public string DriverLicence { get; set; }
        public string MaritalStatus { get; set; }
        public string HomePhone { get; set; }
        public string PhoneBilledTo { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public int NumberOfDependants { get; set; }         //type and name changed
        public string AgesOfDependants { get; set; }        //name changed
        public CurrentAddress CurrentAddress { get; set; }       
        public List<PreviousAddress> PrevAddresses { get; set; }
        public CurrentEmployment CurrentEmployment { get; set; }
        public List<PreviousEmployment> PrevEmployments { get; set; }
        public IncomeAndDebt IncomeAndDebt { get; set; }
        public int BureauScore { get; set; }
        public string ReportURL { get; set; }
}

 public class CurrentAddress
    {
        public string Address { get; set; }
        public string Apt { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string County { get; set; }
        public string Township { get; set; }
        public int YearsAt { get; set; }
        public int MonthsAt { get; set; }
        public string MortgageHolderOrLandlord { get; set; }
        public string LandlordPhone { get; set; }
        public decimal MortgageOrRentPerMonth { get; set; }  //type and name changed
        public string AddressIs { get; set; }
    }

    public class PreviousAddress
    {
        public string Address { get; set; }
        public string Apt { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public int YearsAt { get; set; }
        public int MonthsAt { get; set; }
    }
    public class CurrentEmployment
    {
        public string Employer { get; set; }
        public string Occupation { get; set; }
        public int YearsEmployed { get; set; }
        public int MonthsEmployed { get; set; }
        public string EmployerAddress { get; set; }
        public string EmployerCity { get; set; }
        public string EmployerState { get; set; }
        public string EmployerZIP { get; set; }             //name changed
        public string EmployerPhone { get; set; }
        public decimal HourlyPay { get; set; }              
        public int HoursWorked { get; set; }
        public decimal MonthlyGrossIncome { get; set; }
        public string PayPeriod { get; set; }
    }

 public class PreviousEmployment
    {
        public string Employer { get; set; }
        public string Occupation { get; set; }
        public int YearsEmployed { get; set; }
        public int MonthsEmployed { get; set; }
        public string EmployerPhone { get; set; }
        public string ReasonForLeaving { get; set; }
    }
 
 public class IncomeAndDebt
    {
        public bool ObligatedToMaintenancePayments { get; set; }
        public int YoungestAge { get; set; }
        public bool EverFilledBankruptcy { get; set; }
        public DateTime DischargedDate { get; set; }
        public decimal? Chapter { get; set; }
        public bool EverHadVehicleOrMerchandiseRepossessed { get; set; }
        public DateTime RepossessedDate { get; set; }
        public string TypeRepossessed { get; set; }
        public decimal PriorVehicleCreditAmountBorrowed { get; set; }
        public decimal AmountOwed { get; set; }
        public string WithWhom { get; set; }
        public string BankName { get; set; }
        public string BankCity { get; set; }
        public decimal CheckingBalance { get; set; }
        public decimal SavingsBalance { get; set; }
        public decimal OtherMonthlyIncome { get; set; }
        public string IncomeSource { get; set; }
        public decimal DownPayment { get; set; }
        public decimal MonthlyRentOrMortgagePayment { get; set; }
        public decimal UtilitiesPayment { get; set; }
        public decimal ChildCarePayment { get; set; }
        public decimal cableTVPayment { get; set; }
    }

**Comment by sraghun** [comment]
You may be right.  I will follow up with Mike Downey to see what he says.
