### ISSUE TITLE
Notes put in by a sales person is not visible to the underwriter

### ISSUE THREAD

**Issue by sraghun** [bbuchanan/los-issues#74]
Example: I logged in Walt Lazar and added a note to App #44, but it is not visible to the underwriters.

**Comment by bbuchanan** [comment]
did you save the app? Notes aren't autosaved. Should they be?

**Comment by bbuchanan** [comment]
note: it won't be super easy to do that since the save mechanism is atomic right now. I'd have to break out something separate for the notes.

**Comment by sraghun** [comment]
I did not save the app.  It works once I saved the app.  If Notes cannot be autosaved, can we put a dirty indicator on the record to indicating that there are Unsaved changes?

**Comment by bbuchanan** [comment]
I think that's a good rule regardless! Will have it in the next build.
