### ISSUE TITLE
Approved, Conditionally Approved, Denied status application rules

### ISSUE THREAD

**Issue by sraghun** [bbuchanan/los-issues#75]
If a deal is in Approved, Conditionally Approved or Denied status and is edited and saved by a Sales Person, it should go back to 'Sales' status.  The salesperson would then have to re-submit the deal for Approval or Denial.

If a deal is in one of these statuses and is edited by an 'Underwriter', it needs to go back to Underwriting status until it is Approved or Denied again.

**Comment by bbuchanan** [comment]
This should be implemented. Please give it a try.
