### ISSUE TITLE
Link to Application Form

### ISSUE THREAD

**Issue by sraghun** [bbuchanan/los-issues#78]
In the left hand side menu, create an item called Application and link it to the following page: http://consumerapp.amsws.com/ca_test/#!/application?dealerid=WWD

This will allow sales people to take applications while a customer is in front of them.

**Comment by bbuchanan** [comment]
implemented

**Comment by sraghun** [comment]
Can you please make the link https instead of http?

**Comment by bbuchanan** [comment]
changed, will be available on next deploy
