### ISSUE TITLE
Apps won't load

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#79]
Bill, glad we fixed the co-applicant problem. 
I'm not sure if it's related, but now I'm unable to load an application in the UW tool.

https://uw.waterwheeldata.com/order/1abc22de-ad08-4d42-b590-a9bed14a74e1
Do you get the same experience?

**Comment by bbuchanan** [comment]
Yes, probably whatever the server wasn't expecting to be null also the client isn't expecting it either. I'll see what I can find.

**Comment by bbuchanan** [comment]
Heya Mike, I think I have addressed the issue and it's deployed to production. One thing to note (and it threw me for a loop), the web browser was "smart" and cached the app for me. I exited all browsers and refreshed. Might try this if you're still seeing the problem.
