### ISSUE TITLE
Scoring API - Paytype adjustment

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#80]
Originally, Auto Master sent us pay types using different numbers.
Instead of the 52, 26, 24, 12 values we’re generating, they sent us 0,1,2,3, and 5. 
I would like to have the UW tool call the same Lambda function as the Auto Master scoring button. But to do this, we need to match the exact output AMS produces. 

So…we need to adjust the PayType in the scoring API to produce the following:

When PayType select is X = set it to pass the value Y:

Weekly = 1
Biweekly = 2
Semi-monthly = 3
Monthly = 5
Single Payment = 0

**Comment by sraghun** [comment]
Mike, I think this can be handled internally in the Lambda function by saying 1 and 52 are interchangeable.

**Comment by humike** [comment]
I thought that too, except when they select single payment.

Then it will pass a 1.... but maybe I can use term in those situations to
check too.
Case when paytype = 1 and term = 1 then single payment.

They do happen.

**Comment by bbuchanan** [comment]
This was databased in the QuotePayType table with the column name AmsPayType. The score function uses this column, so if it needs to change ever, you'll be able to make the change in the db instead of the code.
