### ISSUE TITLE
FULL APPLICATION Error

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#84]
So I went through the entire app and filled out every single combination of fields. 

On a full application applicant with previous address, previous employer:
co-applicant with previous address and previous employer
I received this error:

![image](https://user-images.githubusercontent.com/59945434/74265184-11935c00-4cd0-11ea-8346-aad407c80039.png)

**Comment by bbuchanan** [comment]
I am logging the json, but will need some help identifying what you sent. Can you give me some details like the name and address you used as a test?

**Comment by humike** [comment]
Abraham Lincoln is the primary buyer. Should have pensyvalina have as
current employment.
Sent in the last 10 minutes

**Comment by bbuchanan** [comment]
Sadly, didn't add a timestamp to the log, so time doesn't help. I'll look for it now. Thanks!

**Comment by bbuchanan** [comment]
Pretty sure I figured it out. The housing status didn't match with what we had in the database. Adjusted that.
