### ISSUE TITLE
Scoring API - Payment vs Monthly Payment

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#87]
Payment should be the standard payment amount, not the monthly value. 
So remove the last bit of math that transforms the payment to monthly. 

![image](https://user-images.githubusercontent.com/59945434/74274596-52936c80-4ce0-11ea-8883-ee61be87d97d.png)

The monthly payment should continue passing the monthly payment amount.

**Comment by bbuchanan** [comment]
will be addressed in next deploy
