### ISSUE TITLE
Monthly Budget Box - wrong value passed

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#90]
![image](https://user-images.githubusercontent.com/59945434/74275452-e580d680-4ce1-11ea-9be7-93aa89b8ed0c.png)

We need to be passing the "term" and not the "num_of_payments". 

At 156 months ... at $483 is like a mortgage 🏠 
talk about begin ripped off for a car.

**Comment by bbuchanan** [comment]
will be addressed in next deploy
