### ISSUE TITLE
Print Page needs more fields to inform sales person of structure and payment

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#93]
In reviewing the print page, I realized the sales person can only see the information to enter into Auto Master. They don't see anything specific about the structure of the loan to communicate with the customer.

We need to add the following items after Misc line item on the print page:

PayType: 
Payment (Regular based on paytype weekly, monthly, semi-monthly, etc.):
Term: number of months

**Comment by bbuchanan** [comment]
added
