### ISSUE TITLE
Term and Num of Payments broken

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#94]
In the picture below, Term is correct, as it displays the number of months.
Num of Payments is inaccurate. It should show be the number of weekly payments.
This was working before... but it's broken now. 

![image](https://user-images.githubusercontent.com/59945434/74375194-e67f3a00-4dad-11ea-9aeb-43ba566a58da.png)

**Comment by humike** [comment]
Looks like it's mapped to some other field? I tried to change the pay type, and the num of payments doesn't change at all. 

![image](https://user-images.githubusercontent.com/59945434/74375474-60afbe80-4dae-11ea-9964-230d97a3d0c6.png)

**Comment by bbuchanan** [comment]
I think I see what's going on here. The number of payments calculation goes against what is saved to the server last, not the current selection. I'll make the change for it to be dynamic, will take me a few.

**Comment by bbuchanan** [comment]
actually, wasn't as bad as I thought it would be. Will post a fix before I leave this evening.
