### ISSUE TITLE
Desking doesn't seem to work anymore

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#95]
![image](https://user-images.githubusercontent.com/59945434/74375621-a66c8700-4dae-11ea-917b-27faa35f5612.png)
I went through the conditional approval steps and then tried to push to desking. 
Button click does not result in any action.

**Comment by humike** [comment]
There was some sort of delay.... eventually the application went to desking. But it was unclear.

**Comment by humike** [comment]
Can we add some loading popup which states "sending to Auto Master" or something along those lines?
Desking a deal is unclear and also surprisingly slow.

**Comment by bbuchanan** [comment]
Well, this stuff was "if we had time" type of stuff ... but I started working on error reporting (and success reporting). See issue #57. I was able to piggyback a spinner during the save action to give some feedback (and also report success). And yes, posting back to AMS does take a long time and there isn't much I can do about that. :(
