### ISSUE TITLE
Application 48, missing primary buyer?

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#96]
This application has a co-applicant, but not an applicant. 
I tried to swap them back and forth. 

Are there any restrictions that would prevent a blank co-applicant from appearing?

**Comment by humike** [comment]
![image](https://user-images.githubusercontent.com/59945434/74381898-5dbacb00-4dba-11ea-9f27-ba6609e3a792.png)

**Comment by bbuchanan** [comment]
App 48 seems to be loading OK now. Not sure if this was fixed inadvertently or what, but I'm going to close it. Reopen if you see it happen again.
