### ISSUE TITLE
Score is running without APR or term

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#97]
Must have missed this in an earlier issue, but it looks like the rescore button works without any structure. Account must have an APR, paytype, and term selected to continue. 

![image](https://user-images.githubusercontent.com/59945434/74386984-649b0b00-4dc5-11ea-9dec-6c9afc420401.png)

**Comment by bbuchanan** [comment]
There was never any validation when you hit the rescore button, only when you save the app.

The app requires all of the fields to be populated. Should this be the case for rescore or is this a special type of validation where we only require some fields?

**Comment by humike** [comment]
So in order to score, the UW needs to review the structure of the application. They cannot hit score without a structure. Let's make the following fields required so they must populate in order to hit the score button. 

APR and Term

**Comment by bbuchanan** [comment]
will be addressed in next build.
