### ISSUE TITLE
Records Per Page Error is Back

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#99]
On the sales queue page, when I select show 50 records per page, I receive an error and the screen goes blank. 

![image](https://user-images.githubusercontent.com/59945434/75257516-16b5d800-57b3-11ea-9b40-70279f157600.png)

Do you see the same problem?

**Comment by bbuchanan** [comment]
I figured this out, it wasn't paging related. It was data related. I had started "cleaning out" the test data before a go live, so some applications had no customers causing this to blow up. I deleted the erroneous apps.
